blog_category:
  type: string
  default: ""
blog_tag:
  type: list
  list_type: tag
  default: ""
image_size:
  type: enum
  default: "full width"
  choices:
    - no image
    - full width
    - centered
image_position:
  type: enum
  default: "above title"
  choices:
    - above title
    - below title
dropcap_enabled:
  type: bool
  default: false
mobile_enabled:
  type: bool
  default: false
